query ListAllInsights @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it only retrieves insights.") {
  insights {
    id
    title
    summary
    content
    audioUrl
    audioMood
    tags
    createdAt
    published
    author {
      displayName
      profilePictureUrl
    }
  }
}

query GetMyProjects @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it retrieves projects marked as published.") {
  projects(where: {published: {eq: true}}, orderBy: [{order: ASC}]) {
    id
    title
    description
    techStack
    liveDemoUrl
    repositoryUrl
    startDate
    endDate
    published
    order
  }
}

query GetUserProfile($id: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as user profiles are public information.") {
  user(id: $id) {
    id
    displayName
    bio
    profilePictureUrl
    githubUrl
    linkedinUrl
  }
}

query ListTimeline @auth(level: PUBLIC, insecureReason: "Timeline is public information.") {
  timelines(orderBy: [{startDate: DESC}]) {
    id
    title
    description
    startDate
    endDate
    imageUrl
    published
  }
}