extend type Mutation {
  """
  ✨ Insert a single `Comment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  comment_insert(
    """
    Data object to insert into the table.
    """
    data: Comment_Data!
  ): Comment_KeyOutput! @fdc_generated(from: "Comment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CommentProfile` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  commentProfile_insert(
    """
    Data object to insert into the table.
    """
    data: CommentProfile_Data!
  ): CommentProfile_KeyOutput! @fdc_generated(from: "CommentProfile", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Insight` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  insight_insert(
    """
    Data object to insert into the table.
    """
    data: Insight_Data!
  ): Insight_KeyOutput! @fdc_generated(from: "Insight", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Project` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  project_insert(
    """
    Data object to insert into the table.
    """
    data: Project_Data!
  ): Project_KeyOutput! @fdc_generated(from: "Project", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ProjectArticle` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  projectArticle_insert(
    """
    Data object to insert into the table.
    """
    data: ProjectArticle_Data!
  ): ProjectArticle_KeyOutput! @fdc_generated(from: "ProjectArticle", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Timeline` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  timeline_insert(
    """
    Data object to insert into the table.
    """
    data: Timeline_Data!
  ): Timeline_KeyOutput! @fdc_generated(from: "Timeline", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Comment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  comment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Comment_Data!]!
  ): [Comment_KeyOutput!]! @fdc_generated(from: "Comment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CommentProfile` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  commentProfile_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CommentProfile_Data!]!
  ): [CommentProfile_KeyOutput!]! @fdc_generated(from: "CommentProfile", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Insight` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  insight_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Insight_Data!]!
  ): [Insight_KeyOutput!]! @fdc_generated(from: "Insight", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Project` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  project_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Project_Data!]!
  ): [Project_KeyOutput!]! @fdc_generated(from: "Project", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ProjectArticle` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  projectArticle_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ProjectArticle_Data!]!
  ): [ProjectArticle_KeyOutput!]! @fdc_generated(from: "ProjectArticle", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Timeline` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  timeline_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Timeline_Data!]!
  ): [Timeline_KeyOutput!]! @fdc_generated(from: "Timeline", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Comment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Comment`.
  """
  comment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Comment_Data!
  ): Comment_KeyOutput! @fdc_generated(from: "Comment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CommentProfile` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CommentProfile`.
  """
  commentProfile_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CommentProfile_Data!
  ): CommentProfile_KeyOutput! @fdc_generated(from: "CommentProfile", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Insight` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Insight`.
  """
  insight_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Insight_Data!
  ): Insight_KeyOutput! @fdc_generated(from: "Insight", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Project` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Project`.
  """
  project_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Project_Data!
  ): Project_KeyOutput! @fdc_generated(from: "Project", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ProjectArticle` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProjectArticle`.
  """
  projectArticle_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ProjectArticle_Data!
  ): ProjectArticle_KeyOutput! @fdc_generated(from: "ProjectArticle", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Timeline` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Timeline`.
  """
  timeline_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Timeline_Data!
  ): Timeline_KeyOutput! @fdc_generated(from: "Timeline", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Comment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Comment`.
  """
  comment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Comment_Data!]!
  ): [Comment_KeyOutput!]! @fdc_generated(from: "Comment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CommentProfile` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CommentProfile`.
  """
  commentProfile_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CommentProfile_Data!]!
  ): [CommentProfile_KeyOutput!]! @fdc_generated(from: "CommentProfile", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Insight` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Insight`.
  """
  insight_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Insight_Data!]!
  ): [Insight_KeyOutput!]! @fdc_generated(from: "Insight", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Project` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Project`.
  """
  project_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Project_Data!]!
  ): [Project_KeyOutput!]! @fdc_generated(from: "Project", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ProjectArticle` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProjectArticle`.
  """
  projectArticle_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ProjectArticle_Data!]!
  ): [ProjectArticle_KeyOutput!]! @fdc_generated(from: "ProjectArticle", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Timeline` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Timeline`.
  """
  timeline_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Timeline_Data!]!
  ): [Timeline_KeyOutput!]! @fdc_generated(from: "Timeline", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Comment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Comment` or `null` if not found.
  """
  comment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Comment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Comment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Comment_Data!
  ): Comment_KeyOutput @fdc_generated(from: "Comment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CommentProfile` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CommentProfile` or `null` if not found.
  """
  commentProfile_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CommentProfile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CommentProfile_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CommentProfile_Data!
  ): CommentProfile_KeyOutput @fdc_generated(from: "CommentProfile", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Insight` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Insight` or `null` if not found.
  """
  insight_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Insight_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Insight_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Insight_Data!
  ): Insight_KeyOutput @fdc_generated(from: "Insight", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Project` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Project` or `null` if not found.
  """
  project_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Project_Data!
  ): Project_KeyOutput @fdc_generated(from: "Project", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ProjectArticle` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ProjectArticle` or `null` if not found.
  """
  projectArticle_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectArticle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectArticle_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ProjectArticle_Data!
  ): ProjectArticle_KeyOutput @fdc_generated(from: "ProjectArticle", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Timeline` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Timeline` or `null` if not found.
  """
  timeline_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Timeline_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Timeline_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Timeline_Data!
  ): Timeline_KeyOutput @fdc_generated(from: "Timeline", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Comment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  comment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Comment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Comment_Data!
  ): Int! @fdc_generated(from: "Comment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CommentProfile` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  commentProfile_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CommentProfile_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CommentProfile_Data!
  ): Int! @fdc_generated(from: "CommentProfile", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Insight` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  insight_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Insight_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Insight_Data!
  ): Int! @fdc_generated(from: "Insight", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Project` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  project_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Project_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Project_Data!
  ): Int! @fdc_generated(from: "Project", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ProjectArticle` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  projectArticle_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ProjectArticle_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ProjectArticle_Data!
  ): Int! @fdc_generated(from: "ProjectArticle", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Timeline` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  timeline_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Timeline_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Timeline_Data!
  ): Int! @fdc_generated(from: "Timeline", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Comment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  comment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Comment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Comment_FirstRow
  ): Comment_KeyOutput @fdc_generated(from: "Comment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CommentProfile` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  commentProfile_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CommentProfile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CommentProfile_FirstRow
  ): CommentProfile_KeyOutput @fdc_generated(from: "CommentProfile", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Insight` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  insight_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Insight_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Insight_FirstRow
  ): Insight_KeyOutput @fdc_generated(from: "Insight", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Project` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  project_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow
  ): Project_KeyOutput @fdc_generated(from: "Project", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ProjectArticle` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  projectArticle_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectArticle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectArticle_FirstRow
  ): ProjectArticle_KeyOutput @fdc_generated(from: "ProjectArticle", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Timeline` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  timeline_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Timeline_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Timeline_FirstRow
  ): Timeline_KeyOutput @fdc_generated(from: "Timeline", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Comment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  comment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Comment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Comment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CommentProfile` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  commentProfile_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CommentProfile_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CommentProfile", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Insight` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  insight_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Insight_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Insight", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Project` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  project_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Project_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Project", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ProjectArticle` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  projectArticle_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ProjectArticle_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ProjectArticle", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Timeline` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  timeline_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Timeline_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Timeline", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
